services:
  - type: web
    name: english-learning-bot
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TIMEZONE
        value: Asia/Tashkent
      - key: NODE_VERSION
        value: 20.0.0
      - key: RENDER_EXTERNAL_URL
        sync: false
