services:
  - type: web
    name: english-learning-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free